### ISSUE TITLE
Exception running keylime_webapp

### ISSUE THREAD

**Issue by RUKip** [keylime/keylime-vagrant-ansible-tpm-emulator#43] opened 2020-10-20 21:39 UTC
Running the keylime_webapp inside the VM throws an exception:
> Traceback (most recent call last):
>   File "/usr/local/bin/keylime_webapp", line 11, in <module>
>     load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_webapp')()
>   File "/usr/local/lib/python3.7/site-packages/keylime-0.0.0-py3.7.egg/keylime/cmd/webapp.py", line 15, in main
>     tenant_webapp.main()
>   File "/usr/local/lib/python3.7/site-packages/keylime-0.0.0-py3.7.egg/keylime/tenant_webapp.py", line 640, in main
>     'Static resource directory could not be found in %s!' % (root_dir))
> Exception: Static resource directory could not be found in /usr/local/lib/python3.7/site-packages/keylime-0.0.0-py3.7.egg/keylime!

**Comment by MartinMa28** [comment] 2021-02-21 23:22
I run into this problem as well in the VM.
To reproduce it:
1. `vagrant up --provision`
2. `vagrant ssh`
3. `sudo su`
4. `keylime_webapp`

Error log:
Traceback (most recent call last):
  File "/usr/local/bin/keylime_webapp", line 33, in <module>
    sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_webapp')())
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/cmd/webapp.py", line 15, in main
    tenant_webapp.main()
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/tenant_webapp.py", line 694, in main
    raise Exception(
Exception: Static resource directory could not be found in /usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime!

**Comment by THS-on** [comment] 2023-07-26 20:59
Closing, because the webapp no longer exists.

**Closed by THS-on** 2023-07-26 20:59 UTC
